server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}

app.minio.endpoint=http://minio:9000
app.minio.access-key=${MINIO_ACCESS_KEY}
app.minio.secret-key=${MINIO_SECRET_KEY}
app.minio.bucket=${MINIO_BUCKET}
app.minio.max-file-size=${MINIO_MAX_FILE_SIZE}
app.minio.presign-ttl-seconds=${MINIO_PRESIGN_TTL_SECONDS}