spring.application.name=employee-service

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${ACTIVE_PROFILE}

internal.api-key=${INTERNAL_API_KEY}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=@project.version@
info.app.java=${java.version}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.innowise=TRACE
